@baseUrl = http://localhost:8000/api/v1
@accessToken = YOUR_ACCESS_TOKEN

### Register
POST {{baseUrl}}/auth/register
Accept: application/json
Content-Type: application/json

{
    "fullname": "John Smith",
    "username": "johnsmith2001it@gmail.com",
    "password": "1106",
    "password_confirmation": "1106"
}

### Login
POST {{baseUrl}}/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "an@example.com",
    "password": "12345678"
}

### Get current user
GET {{baseUrl}}/auth/me
Accept: application/json
Authorization: Bearer {{accessToken}}

### Logout current device
POST {{baseUrl}}/auth/logout
Accept: application/json
Authorization: Bearer {{accessToken}}

### Logout all devices
POST {{baseUrl}}/auth/logout-all
Accept: application/json
Authorization: Bearer {{accessToken}}
